import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>


        <header style={{backgroundColor: "#333", color: "#fff", padding: "10px"}}>
            <h1>Your Company Name</h1>
            <p>Tagline or description goes here</p>
        </header>

        {children}

        <footer
            style={{
                backgroundColor: "#333",
                color: "#fff",
                padding: "10px",
                bottom: "0",
                width: "100%",
                position: "fixed"
            }}>
            <p>&copy; 2024 Your Company Name. All rights reserved.</p>
        </footer>


        </body>
        </html>
    )
}
